name             'chef-owncloud'
maintainer       'PE, pf.'
maintainer_email 'peychart@mail.pf'
license          'GNU Public License 3.0'
description      'Installs/Configures chef-owncloud'
long_description 'Installs/Configures chef-owncloud'
version          '0.1.0'
depends          'chef-iscsiadm'
depends          'chef-lvm'
depends          'chef-mkswap'
depends          'chef-iptables'
